### ISSUE TITLE
Humm, Mr, Zijlstra, i suppose.

### ISSUE THREAD

**Issue by JOSMAN-UE** [arjentz/dedekind-wiedemann#1]

**Comment by atezet** [comment]
Hey there, sorry for my late reply but I couldn't find the time earlier. At the moment I am not active at the University of Groningen anymore, but I could probably get you in contact with someone.

At the time of writing my code, I was very enthusiastic about using C++ for anything I could make it work, and therefore I chose to do it in C++. But after the project, I figured that a dedicated C program would probably have been the better way. I see that you've already made quite some optimisations and you are getting good results. What are your plans from here?

Also, what exactly can I provide you with, s.t. you can continue with your research?
