### ISSUE TITLE
Paper link is broken

### ISSUE THREAD

**Issue by MrOnlineCoder** [arjentz/dedekind-wiedemann#2]
Hey, thanks for publishing your work!

I am trying to do some research on similiar topic right now as a bachelor project too, and would really appreciate if you could fix a working link for your paper, because the one in README is broken: http://irs.ub.rug.nl/dbi/51deb7b40990d

Thanks in advance!

**Comment by atezet** [comment]
Thanks for pointing that out. They renamed the faculty (to an English variant), rendering all old links useless. I updated the link with a new one. Good luck!
